### ISSUE TITLE
No reply receives from SQL server

### ISSUE THREAD

**Issue by naushadck** [mclap/tdslite#1]
I am using this in windows. The system is not getting any reply from SQL server. 
It sends the data to sql server. However no reply receives from SQL.

Any support on this.

**Comment by mclap** [comment]
Hello,

This library does have support for password-based authentication (SQL Server Authentication) only. Current state of the library does not provide support for the Kerberos/NTLM authentication (Windows Authentication).

See also:
https://docs.microsoft.com/en-us/sql/relational-databases/security/choose-an-authentication-mode?view=sql-server-ver15

Target platform is Linux/FreeBSD only. I have not tried to run this client under Windows.

**Comment by naushadck** [comment]
Hi,

I am using password-based authentication (SQL Server Authentication) only. SQL server is setup in mixed mode, i am always using SQL server authentication.

Can i know if there is any diffence in TDS for Linux.  If so, i can do the changes accordingly. And test it.

**Comment by mclap** [comment]
**Short**

There is no official Windows port of my library. I do not understand how I can help you.

**Long**

At time of writing (near 2012) this library was able to connect to SQL server and execute simple query.

As there is no way to build this library unchanged to run under Windows, I suppose you are using some modified version of my library.

By building for Windows I mean official the tools from Microsoft, e.g. Visual Studio C++ and Microsoft C++ compiler.

**Comment by naushadck** [comment]
Long
------
I am used the cloed one from this repository. 
Since you confirmed that it will not work under windows, then there is no way i can use the same in windows.
